// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package structcopy

type ConverterImpl struct{}

func (c *ConverterImpl) Convert(source Input) Output {
	var structcopyOutput Output
	structcopyOutput.Name = source.Name
	structcopyOutput.Age = source.Nested.AgeInYears
	return structcopyOutput
}
func (c *ConverterImpl) ConvertItems(source []Input) []Output {
	var structcopyOutputList []Output
	if source != nil {
		structcopyOutputList = make([]Output, len(source))
		for i := 0; i < len(source); i++ {
			structcopyOutputList[i] = c.Convert(source[i])
		}
	}
	return structcopyOutputList
}
